Fatal error: Uncaught Exception: Cause count to fail in %s
Stack trace:
#0 [internal function]: MyHeap->count()
#1 %s count(Object(MyHeap))
#2 {main}
  thrown in %s on line %d