Exception: 1 in %s:%d
Stack trace:
#0 %s(%d): test()
#1 {main}

Next Exception: 3 in %s:%d
Stack trace:
#0 %s(%d): test()
#1 {main}