
---- EXPECTED OUTPUT
Fatal error: Uncaught Exception: ops 2 in %sbug53511.php:11
Stack trace:
#0 %sbug53511.php(17): test()
#1 {main}

Next Exception: ops 1 in %sbug53511.php:4
Stack trace:
#0 %sbug53511.php(12): Foo->__destruct()
#1 %sbug53511.php(17): test()
#2 {main}
  thrown in %sbug53511.php on line 4
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Exception: ops 2 in /root/php-src/Zend/tests/bug53511.php:11
Stack trace:
#0 /root/php-src/Zend/tests/bug53511.php(17): test()
#1 {main}

Next Exception: ops 1 in /root/php-src/Zend/tests/bug53511.php:4
Stack trace:
#0 /root/php-src/Zend/tests/bug53511.php(12): Foo->__destruct()
#1 /root/php-src/Zend/tests/bug53511.php(17): test()
#2 {main}
  thrown in /root/php-src/Zend/tests/bug53511.php on line 4
---- FAILED
