
---- EXPECTED OUTPUT
Fatal error: Uncaught Exception: Parameter 1 to Foo\{closure}() expected to be a reference, value given in %sbug74164.php:%d
Stack trace:
#0 [internal function]: Foo\{closure}(%s)
#1 %sbug74164.php(%d): call_user_func(%s)
#2 {main}
  thrown in %sbug74164.php on line %d
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory

Fatal error: Uncaught Exception: Parameter 1 to Foo\{closure}() expected to be a reference, value given in /root/php-src/Zend/tests/bug74164.php:6
Stack trace:
#0 [internal function]: Foo\{closure}(2, 'Parameter 1 to ...', '/root/php-src/Z...', 9, Array)
#1 /root/php-src/Zend/tests/bug74164.php(9): call_user_func(Object(Closure), 'not_an_array_va...')
#2 {main}
  thrown in /root/php-src/Zend/tests/bug74164.php on line 6
---- FAILED
