
---- EXPECTED OUTPUT
Exception in %s:%d
Stack trace:
#0 %s(%d): Obj->__get('x')
#1 {main}
Exception in %s:%d
Stack trace:
#0 %s(%d): Obj->__get('x')
#1 {main}
Exception in %s:%d
Stack trace:
#0 %s(%d): Obj->__get('x')
#1 {main}
---- ACTUAL OUTPUT
Failed loading /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so:  /opt/php-7.1/lib/php/extensions/debug-non-zts-20160303/xdebug.so: cannot open shared object file: No such file or directory
Exception in /root/php-src/Zend/tests/rope_with_exception.php:5
Stack trace:
#0 /root/php-src/Zend/tests/rope_with_exception.php(12): Obj->__get('x')
#1 {main}
Exception in /root/php-src/Zend/tests/rope_with_exception.php:5
Stack trace:
#0 /root/php-src/Zend/tests/rope_with_exception.php(21): Obj->__get('x')
#1 {main}
Exception in /root/php-src/Zend/tests/rope_with_exception.php:5
Stack trace:
#0 /root/php-src/Zend/tests/rope_with_exception.php(30): Obj->__get('x')
#1 {main}
---- FAILED
